// constants/materiales.js

export const UNIDADES = [
  'UND', 'M', 'M2', 'M3', 'GLN', 'L', 'PAQ', 'BOL', 'MLL', 'KIT',
  'JGO', 'KG', 'T', 'BOT', 'BLD', 'CAJ', 'CIL', 'PAR', 'PIE', 'ROL'
];

export const TIPOS_MATERIAL = [
  { codigo: 'Z001', nombre: 'REPUESTOS ESPECIFICOS' },
  { codigo: 'Z002', nombre: 'REPUESTOS GENERALES' },
  { codigo: 'Z003', nombre: 'MAT. AUXILIARES' },
  { codigo: 'Z004', nombre: 'MAT. DIVERSOS' },
  { codigo: 'Z005', nombre: 'CONSUMIBLES' },
  { codigo: 'Z006', nombre: 'COMBUSTIBLES' },
  { codigo: 'Z007', nombre: 'MATERIAS PRIMAS' },
  { codigo: 'Z008', nombre: 'ENVASES' },
  { codigo: 'Z009', nombre: 'EMBALAJE' },
  { codigo: 'Z010', nombre: 'ACTIVO FIJOS' },
  { codigo: 'Z011', nombre: 'MATERIALES NO VALORADOS' },
  { codigo: 'Z012', nombre: 'MERCADERIA' },
  { codigo: 'Z013', nombre: 'SERVICIO DE VENTA' },
  { codigo: 'Z014', nombre: 'PRODUCTOS SEMI ELABORADOS' },
  { codigo: 'Z015', nombre: 'PRODUCTOS TERMINADOS' },
];

export const GRUPOS_ARTICULOS = {
  'Z001': [
    { codigo: 'BLOQUE001', nombre: 'RPTOS. BLOQUETERA' },
    { codigo: 'HORMIG001', nombre: 'RPTOS. PLANTA DOSIFICADORAS' },
    { codigo: 'HIDRO001', nombre: 'REPRESAMIENTO' },
    { codigo: 'HIDRO002', nombre: 'GENERACION/TRANSFORMACION' },
    { codigo: 'HIDRO003', nombre: 'TRANSMISION' },
    { codigo: 'HIDRO004', nombre: 'AUXILIARES MECANICOS' },
    { codigo: 'HIDRO005', nombre: 'AUXILIARES ELECTRICOS' },
    { codigo: 'TCHCC001', nombre: 'GEN. ENERG. A GAS' },
    { codigo: 'TCHCC002', nombre: 'GEN. ENERG. A VAPOR' },
    { codigo: 'TCHCC003', nombre: 'GEN. DE VAPOR' },
    { codigo: 'TCHCC004', nombre: 'SIST. AUXILIARES' },
    { codigo: 'TCHCC005', nombre: 'OTROS ESPECIFICOS' },
    { codigo: 'CEMENT001', nombre: 'TRITURACION' },
    { codigo: 'CEMENT002', nombre: 'MOLINO DE BOLAS' },
    { codigo: 'CEMENT003', nombre: 'CLINKERIZACION' },
    { codigo: 'CEMENT004', nombre: 'PRENSAS' },
    { codigo: 'CEMENT005', nombre: 'ENVASADORAS' },
    { codigo: 'CEMENT006', nombre: 'COLECTOR-CARBON-ELEV' },
  ],
  'Z002': [
    { codigo: 'COMPRE001', nombre: 'AERZENER' },
    { codigo: 'COMPRE002', nombre: 'ATLAS COPCO' },
    { codigo: 'COMPRE003', nombre: 'CLAUDIUS PETERS' },
    { codigo: 'COMPRE004', nombre: 'FULLER KOVAKO' },
    { codigo: 'COMPRE005', nombre: 'GARDNER DENVER' },
    { codigo: 'COMPRE006', nombre: 'KELLOG' },
    { codigo: 'COMPRE007', nombre: 'SULLAIR' },
    { codigo: 'COMPRE008', nombre: 'TUTHILL' },
    { codigo: 'COMPRE009', nombre: 'INGERSOLL RAND' },
    { codigo: 'COMPRE010', nombre: 'QUIMCY' },
    { codigo: 'COMPRE099', nombre: 'VARIOS - COMPRESORAS' },
    { codigo: 'ELETRI001', nombre: 'ARRANCADORES Y TABLEROS' },
    { codigo: 'ELETRI003', nombre: 'CONDENSADORES' },
    { codigo: 'ELETRI004', nombre: 'CONTACTORES, FUSIBLES Y RELES' },
    { codigo: 'ELETRI005', nombre: 'X-ILUMINACION Y ACC.' },
    { codigo: 'ELETRI006', nombre: 'INTERRUPTORES Y GUARDAMOTORES' },
    { codigo: 'ELETRI007', nombre: 'X-MATERIAL ELECTRICO' },
    { codigo: 'ELETRI008', nombre: 'MOTORES Y ACC.' },
    { codigo: 'ELETRI009', nombre: 'MOTOREDUCTORES Y ACC.' },
    { codigo: 'ELETRI010', nombre: 'TRANSFORMADORES Y ACC.' },
    { codigo: 'ELETRI011', nombre: 'VENTILADORES' },
    { codigo: 'ELETRI012', nombre: 'EQUIPO DE MEDIA TENSIÓN' },
    { codigo: 'ELETRI013', nombre: 'EQUIPO DE ALTA TENSIÓN' },
    { codigo: 'ELETRI099', nombre: 'VARIOS - ELECTRICO' },
    { codigo: 'ELETRO001', nombre: 'ACTUADORES MOTORIZADOS Y ELECTRONEUMATICOS' },
    { codigo: 'ELETRO002', nombre: 'COMPONENTES ELECTRONICOS' },
    { codigo: 'ELETRO003', nombre: 'DOSIFICADORES Y BALANZAS' },
    { codigo: 'ELETRO004', nombre: 'ELEMENTOS DE POSICION' },
    { codigo: 'ELETRO005', nombre: 'EQUIPOS DE COMUNICACION' },
    { codigo: 'ELETRO006', nombre: 'EQUIPOS DE LABORATORIO' },
    { codigo: 'ELETRO007', nombre: 'EQUIPOS ELECTRONICOS' },
    { codigo: 'ELETRO008', nombre: 'INSTRUMENTOS DE MEDICION' },
    { codigo: 'ELETRO009', nombre: 'LABORATORIO RAYOS X' },
    { codigo: 'ELETRO010', nombre: 'PLC Y OTROS AUTOMATIZACION' },
    { codigo: 'ELETRO011', nombre: 'TRANSDUCTORES Y SENSORES ANALOGICOS Y DIGITALES' },
    { codigo: 'ELETRO012', nombre: 'VARIADORES DE VELOCIDAD' },
    { codigo: 'ELETRO013', nombre: 'SISTEMAS DE LUBRICACION' },
    { codigo: 'ELETRO014', nombre: 'X-EQUIPOS DE COMPUTO' },
    { codigo: 'ELETRO099', nombre: 'VARIOS - ELECTRONICO' },
    { codigo: 'RODCHU001', nombre: 'RODAMIENTOS' },
    { codigo: 'RODCHU002', nombre: 'SOPORTES' },
    { codigo: 'RODCHU003', nombre: 'RETENES' },
    { codigo: 'RODCHU004', nombre: 'ACC. RODAMIENTOS Y SOPORTES' },
    { codigo: 'RODCHU005', nombre: 'MANGUITOS' },
    { codigo: 'SERAUX001', nombre: 'MUELLE CONCHAN' },
    { codigo: 'SERAUX002', nombre: 'PLANTA OSMOSIS INVERSA' },
    { codigo: 'SERAUX003', nombre: 'PLANTA TRATAM AGUA RESID (PTAR-ATOCON)' },
    { codigo: 'SERAUX004', nombre: 'RPTOS. AIRE ACONDICIONADO' },
    { codigo: 'SERAUX005', nombre: 'RPTOS. CENTRAL HIDROELEC. (CARPAPATA)' },
    { codigo: 'SERAUX006', nombre: 'RPTOS. MOTORES DIESEL' },
    { codigo: 'SERAUX007', nombre: 'SERVICIOS AUX. L1 Y L2' },
    { codigo: 'SERAUX008', nombre: 'SUBESTACIONES ELECTRICAS' },
    { codigo: 'SERAUX009', nombre: 'RPTOS. ASCENSORES' },
    { codigo: 'SERAUX010', nombre: 'RPTOS. MOTORES AUXILIARES' },
    { codigo: 'SERAUX011', nombre: 'TERMOCHILCA-STO DOMINGO' },
    { codigo: 'SERAUX012', nombre: 'PLANTA TERMICA EX GEA' },
    { codigo: 'SERAUX013', nombre: 'RPTOS CENTRAL HIDROELEC HIDROMARAÑON' },
    { codigo: 'SERAUX014', nombre: 'RTOS DRAKE AGREGADOS' },
    { codigo: 'SERAUX015', nombre: 'RPTOS ANALIZADORES DE GASES' },
    { codigo: 'SERAUX099', nombre: 'VARIOS - SERVICIOS AUXILIARES' },
    { codigo: 'TRANSP001', nombre: 'BARREDORAS' },
    { codigo: 'TRANSP002', nombre: 'BOMBONAS' },
    { codigo: 'TRANSP003', nombre: 'CAMIONES' },
    { codigo: 'TRANSP004', nombre: 'CARGADORES' },
    { codigo: 'TRANSP005', nombre: 'DECOSTRADOR' },
    { codigo: 'TRANSP006', nombre: 'GRUAS' },
    { codigo: 'TRANSP007', nombre: 'MONTACARGAS' },
    { codigo: 'TRANSP008', nombre: 'PAVIMENTADORA' },
    { codigo: 'TRANSP009', nombre: 'CAMION MIXER' },
    { codigo: 'TRANSP010', nombre: 'CAMION PLUMA' },
    { codigo: 'TRANSP099', nombre: 'VARIOS - TRANSPORTES' },
    { codigo: 'ACOPLA001', nombre: 'ACOPLAMIENTOS' },
    { codigo: 'ACOPLA002', nombre: 'ACCESORIOS PARA ACOPLAMIENTOS' },
    { codigo: 'MECANI001', nombre: 'ANILLOS RPTOS.' },
    { codigo: 'MECANI002', nombre: 'CASQUILLOS RPTOS.' },
    { codigo: 'MECANI003', nombre: 'CILINDROS RPTOS.' },
    { codigo: 'MECANI004', nombre: 'CHAPAS RPTOS.' },
    { codigo: 'MECANI005', nombre: 'EJES RPTOS.' },
    { codigo: 'MECANI006', nombre: 'FILTROS RPTOS.' },
    { codigo: 'MECANI007', nombre: 'RESORTES RPTOS.' },
    { codigo: 'MECANI008', nombre: 'SOPORTES RPTOS.' },
    { codigo: 'MECANI009', nombre: 'TUBOS RPTOS.' },
    { codigo: 'MECANI010', nombre: 'VALVULAS RPTOS.' },
    { codigo: 'MECANI011', nombre: 'MANGAS Y CANASTILLAS' },
    { codigo: 'MECANI012', nombre: 'MANGUERAS RPTOS.' },
    { codigo: 'MECANI013', nombre: 'SELLOS MECANICOS' },
    { codigo: 'MECANI014', nombre: 'BOMBAS PARA HORMIGON RPTOS' },
    { codigo: 'MECANI099', nombre: 'VARIOS - MECANICOS' },
    { codigo: 'SPROCK001', nombre: 'SPROCKETS' },
    { codigo: 'SPROCK002', nombre: 'CADENAS Y ACC.' },
    { codigo: 'SPROCK003', nombre: 'RUEDAS DENTADAS' },
  ],
  'Z003': [
    { codigo: 'ACFETB001', nombre: 'ANGULOS' },
    { codigo: 'ACFETB002', nombre: 'BARRAS Y BOCINAS' },
    { codigo: 'ACFETB003', nombre: 'EJES' },
    { codigo: 'ACFETB004', nombre: 'LAMINAS Y PLATINAS' },
    { codigo: 'ACFETB005', nombre: 'MATERIALES PARA SOLDAR TUBERIA' },
    { codigo: 'ACFETB006', nombre: 'PLANCHAS' },
    { codigo: 'ACFETB007', nombre: 'PLANCHAS ESPECIALES' },
    { codigo: 'ACFETB008', nombre: 'TUBOS' },
    { codigo: 'ACFETB009', nombre: 'VIGAS Y CANALES' },
    { codigo: 'ACFETB099', nombre: 'VARIOS - ACEROS Y FIERROS' },
    { codigo: 'FERRET001', nombre: 'ABRASIVOS' },
    { codigo: 'FERRET002', nombre: 'ABRAZADERAS, GRAMPAS Y ACOPLES' },
    { codigo: 'FERRET003', nombre: 'ADITIVOS, PEGAMENTOS Y SILICONAS' },
    { codigo: 'FERRET004', nombre: 'CABOS, SOGAS Y ESLINGA' },
    { codigo: 'FERRET005', nombre: 'GRASERAS, LUBRICADORES Y OTROS' },
    { codigo: 'FERRET006', nombre: 'HERRAMIENTAS' },
    { codigo: 'FERRET007', nombre: 'MANOMETROS' },
    { codigo: 'FERRET008', nombre: 'MATERIALES DE CONSTRUCCION' },
    { codigo: 'FERRET009', nombre: 'NIPLERIA Y FITTINGS' },
    { codigo: 'FERRET010', nombre: 'PINTURAS Y SUS SOLVENTES' },
    { codigo: 'FERRET011', nombre: 'SOLVENTES, LIMPIADORES, DESENGRASADORES' },
    { codigo: 'FERRET012', nombre: 'VALVULAS' },
    { codigo: 'FERRET013', nombre: 'SUMINISTROS ELECTRIC' },
    { codigo: 'FERRET014', nombre: 'ILUMINACION Y ACC.' },
    { codigo: 'FERRET015', nombre: 'ESCOBILLAS CARBON' },
    { codigo: 'FERRET099', nombre: 'VARIOS - FERRETERIA' },
    { codigo: 'PERNER001', nombre: 'ANILLOS DE SEGURIDAD SEEGER' },
    { codigo: 'PERNER002', nombre: 'ARANDELAS' },
    { codigo: 'PERNER003', nombre: 'PASADORES' },
    { codigo: 'PERNER004', nombre: 'PERNOS ESTANDAR' },
    { codigo: 'PERNER005', nombre: 'PERNOS HILTI' },
    { codigo: 'PERNER006', nombre: 'PINES' },
    { codigo: 'PERNER007', nombre: 'PRISIONEROS' },
    { codigo: 'PERNER008', nombre: 'STOVE BOLTS' },
    { codigo: 'PERNER009', nombre: 'TORNILLOS' },
    { codigo: 'PERNER010', nombre: 'TUERCAS' },
    { codigo: 'PERNER011', nombre: 'PERNOS ESPECIALES' },
    { codigo: 'PERNER012', nombre: 'PERNOS, TUERCAS Y ARANDELAS N/P' },
    { codigo: 'PERNER099', nombre: 'VARIOS - PERNERIA' },
  ],
  'Z004': [
    { codigo: 'MEDAMB001', nombre: 'ABONOS E INSECTICIDAS' },
    { codigo: 'MEDAMB002', nombre: 'EQUIPOS DE MEDIO AMBIENTE' },
    { codigo: 'MEDAMB003', nombre: 'MATERIALES PTAR' },
    { codigo: 'MEDAMB004', nombre: 'ZOOLÓGICO' },
    { codigo: 'MERCHA001', nombre: 'IMAGEN INSTITUCIONAL' },
    { codigo: 'MERCHA002', nombre: 'RECURSOS HUMANOS' },
    { codigo: 'MISCEL001', nombre: 'AGUA DE MESA, ALIMENTOS Y BEBIDAS' },
    { codigo: 'MISCEL002', nombre: 'ARTEF. ELECTRICOS/ELECTRONICOS' },
    { codigo: 'MISCEL003', nombre: 'ART. DE LIMPIEZA, BAÑOS Y OTROS' },
    { codigo: 'MISCEL004', nombre: 'MANTAS, CAJAS Y PLASTICOS' },
    { codigo: 'MISCEL006', nombre: 'MEDICINAS' },
    { codigo: 'MISCEL007', nombre: 'MUEBLES Y ENSERES' },
    { codigo: 'MISCEL008', nombre: 'ADOKING Y BLOQUES DE 2DA' },
    { codigo: 'MISCEL009', nombre: 'ART. CAMPAÑA NAVIDEÑA' },
    { codigo: 'MISCEL010', nombre: 'PRECINTOS SEGURIDAD' },
    { codigo: 'MISCEL011', nombre: 'EQUIPOS DE COMPUTO' },
    { codigo: 'MISCEL090', nombre: 'OBSOLETO-BAJA-DETER' },
    { codigo: 'MISCEL099', nombre: 'BRD-VARIOS MISCELANEOS' },
    { codigo: 'SEGURI001', nombre: 'EPPS' },
    { codigo: 'SEGURI002', nombre: 'EQUIPOS DE SEGURIDAD' },
    { codigo: 'SEGURI003', nombre: 'UNIFORMES Y ROPA DE TRABAJO' },
    { codigo: 'UTILES001', nombre: 'FORMUL FORMATO IMPTA' },
    { codigo: 'UTILES002', nombre: 'LIBROS, MANUALES Y CATALOGOS' },
    { codigo: 'UTILES003', nombre: 'SUMINISTROS PARA COMPUTO' },
    { codigo: 'UTILES004', nombre: 'UTILES' },
  ],
  'Z005': [
    { codigo: 'CUEMOL001', nombre: 'BOLAS DE ACERO' },
    { codigo: 'CUEMOL002', nombre: 'BOLAS DE ACERO USADAS' },
    { codigo: 'CUEMOL003', nombre: 'CILINDROS DE ACERO (CYLPEBS)' },
    { codigo: 'EXPLOS001', nombre: 'EXPLOSIVOS' },
    { codigo: 'EXPLOS002', nombre: 'ACC. VOLADURA' },
    { codigo: 'GASIND001', nombre: 'GASES INDUSTRIALES' },
    { codigo: 'GASIND002', nombre: 'ACC. GASES INDUSTRIALES' },
    { codigo: 'LABTCC001', nombre: 'MATERIALES DE LABORATORIO' },
    { codigo: 'LABTCC002', nombre: 'BIENES FISCALIZADOS' },
    { codigo: 'LABTCC003', nombre: 'REACTIVOS' },
    { codigo: 'LABTCC004', nombre: 'CRISOLES LABORATORIO' },
    { codigo: 'LUBRIC001', nombre: 'ACEITES' },
    { codigo: 'LUBRIC002', nombre: 'ADITIVOS LUBRICANTES/DIVERSOS' },
    { codigo: 'LUBRIC003', nombre: 'ADITIVOS MOLIENDA/CEMENTO' },
    { codigo: 'LUBRIC004', nombre: 'GRASAS' },
    { codigo: 'MATFUN001', nombre: 'BLINDAJE' },
    { codigo: 'MATFUN002', nombre: 'MARTILLOS' },
    { codigo: 'MATFUN003', nombre: 'PLACAS Y PARRILLAS' },
    { codigo: 'MATFUN004', nombre: 'RUEDAS Y RODILLOS' },
    { codigo: 'MATFUN005', nombre: 'SOPORTES' },
    { codigo: 'MATFUN006', nombre: 'MATERIAL DE SUJECCION' },
    { codigo: 'MATFUN099', nombre: 'VARIOS - MATERIALES FUNDICION' },
    { codigo: 'REFRAC001', nombre: 'ANCLAJES Y AFINES' },
    { codigo: 'REFRAC002', nombre: 'CASTABLES Y AFINES' },
    { codigo: 'REFRAC003', nombre: 'LADRILLOS REFRACTARIOS' },
    { codigo: 'REFRAC004', nombre: 'MATERIALES AISLANTES' },
    { codigo: 'SOLDAD001', nombre: 'SOLDADURAS' },
    { codigo: 'SOLDAD002', nombre: 'ACC. SOLDADURAS' },
    { codigo: 'FAJEMP001', nombre: 'EMPAQUETADURAS' },
    { codigo: 'FAJEMP002', nombre: 'EMPAQUETADURAS DE JEBE' },
    { codigo: 'FAJEMP003', nombre: 'FAJA EN V' },
    { codigo: 'FAJEMP004', nombre: 'LLANTAS Y CAMARAS' },
    { codigo: 'FAJEMP005', nombre: 'LONAS POLYESTER' },
    { codigo: 'FAJEMP006', nombre: 'MANGUERAS LONAS' },
    { codigo: 'FAJEMP007', nombre: 'JUNTAS DE EXPANSION' },
    { codigo: 'FAJEMP008', nombre: 'ANILLO,O-RING,V-RING' },
    { codigo: 'FAJEMP009', nombre: 'CABOS DE AMARRE' },
    { codigo: 'FAJEMP0099', nombre: 'VARIOS - FAJA V, EMPAQUETADURAS' },
    { codigo: 'FAJTRA001', nombre: 'FAJAS TRANSP. Y SIN FIN' },
    { codigo: 'FAJTRA002', nombre: 'POLINES / POLEAS' },
    { codigo: 'FAJTRA003', nombre: 'MATERIALES REPARACION FAJAS' },
    { codigo: 'CABLES001', nombre: 'CABLES DE ENERGIA' },
    { codigo: 'CONBLO001', nombre: 'MOLDES BLOQUES' },
    { codigo: 'CONSAL001', nombre: 'SAL INDUSTRIAL' },
    { codigo: 'CONPRE001', nombre: 'MATERIALES PREANSA' },
    { codigo: 'CONPRE099', nombre: 'VARIOS MAT. PREANSA' },
  ],
  'Z006': [
    { codigo: 'COMBUS001', nombre: 'COMBUSTIBLES GASEOSOS' },
    { codigo: 'COMBUS002', nombre: 'COMBUSTIBLES LIQUIDOS' },
    { codigo: 'COMBUS003', nombre: 'COMBUSTIBLES SOLIDOS' },
  ],
  'Z007': [
    { codigo: 'MPBLOQ001', nombre: 'PIGMENTOS' },
    { codigo: 'MPBLOQ002', nombre: 'PIEDRAS Y ARENA' },
    { codigo: 'MPBLOQ099', nombre: 'VARIOS - MP BLOQUETERA' },
    { codigo: 'MPCEME001', nombre: 'ARCILLA DE TERCEROS' },
    { codigo: 'MPCEME002', nombre: 'CALIZA DE TERCEROS' },
    { codigo: 'MPCEME003', nombre: 'FIERRO DE TERCEROS' },
    { codigo: 'MPCEME004', nombre: 'SILICE DE TERCEROS' },
    { codigo: 'MPCEME005', nombre: 'PUZOLANA DE TERCEROS' },
    { codigo: 'MPCEME006', nombre: 'YESO DE TERCEROS' },
    { codigo: 'MPCEME007', nombre: 'CLINKER IMPORTADO ATO' },
    { codigo: 'MPCEME008', nombre: 'BAUXITA DE TERCEROS' },
    { codigo: 'MPCEME009', nombre: 'ESCORIA AC TERCEROS' },
    { codigo: 'MPCEME010', nombre: 'CENIZA DE CARBON' },
    { codigo: 'MPCEME011', nombre: 'ARENA JP' },
    { codigo: 'MPCEME012', nombre: 'THIRDPARTY DIATOMACE' },
    { codigo: 'MPCEME013', nombre: 'THIRDPARTY QUARRY RE' },
    { codigo: 'MPCEME014', nombre: 'THIRDPARTY ACTVTCARB' },
    { codigo: 'MPCEME015', nombre: 'THIRDPARTY HYDR LIME' },
    { codigo: 'MPPREA001', nombre: 'FIERRO' },
    { codigo: 'MPPREA002', nombre: 'MALLA' },
    { codigo: 'MPPREA003', nombre: 'ARIDOS' },
    { codigo: 'MPPREA004', nombre: 'ADITIVOS' },
    { codigo: 'MPPREA005', nombre: 'CABLE' },
    { codigo: 'MPPREA006', nombre: 'CEMENTO' },
    { codigo: 'MPAGRE001', nombre: 'PIEDRA' },
    { codigo: 'MPAGRE002', nombre: 'ARENA' },
    { codigo: 'MPHORM001', nombre: 'AGUA' },
    { codigo: 'MPHORM002', nombre: 'FIBRAS POLIPROPILENO CONCRETO' },
  ],
  'Z008': [
    { codigo: 'BOLCEM001', nombre: 'BOLSAS TIPO I' },
    { codigo: 'BOLCEM002', nombre: 'BOLSAS TIPO I P' },
    { codigo: 'BOLCEM003', nombre: 'BOLSAS TIPO I PM' },
    { codigo: 'BOLCEM004', nombre: 'BOLSAS TIPO II' },
    { codigo: 'BOLCEM005', nombre: 'BOLSAS TIPO III' },
    { codigo: 'BOLCEM006', nombre: 'BOLSAS TIPO V' },
    { codigo: 'BOLCEM007', nombre: 'BOLSAS FA' },
    { codigo: 'BOLCEM008', nombre: 'BOLSAS TIPO GU' },
    { codigo: 'BOLCEM009', nombre: 'BOLSAS TIPO HS' },
    { codigo: 'BOLCEM010', nombre: 'BOLSAS TIPO I GU' },
    { codigo: 'BOLCEM099', nombre: 'VARIOS - BOLSAS' },
  ],
  'Z009': [
    { codigo: 'EMBALA001', nombre: 'PARIHUELAS' },
    { codigo: 'EMBALA002', nombre: 'BIG BAG' },
    { codigo: 'EMBALA003', nombre: 'X-ESLINGAS' },
    { codigo: 'EMBALA099', nombre: 'VARIOS - EMBALAJE' },
  ],
  'Z010': [
    { codigo: 'VEHLIV001', nombre: 'VEHICULOS LIVINOS' },
    { codigo: 'VEHPES001', nombre: 'VEHICULOS PESADOS' },
    { codigo: 'MUEBLE001', nombre: 'MUEBLE' },
    { codigo: 'COMPUT001', nombre: 'EQ COMPUTO GENERAL' },
    { codigo: 'COMUNI001', nombre: 'EQ COMUNIC GENERAL' },
    { codigo: 'EQSEGU001', nombre: 'EQ SEGURIDAD' },
    { codigo: 'OTREQP001', nombre: 'OTROS EQ GRAL' },
  ],
  'Z011': [
    { codigo: 'NOVALO001', nombre: 'DESMONTES' },
    { codigo: 'NOVALO002', nombre: 'CANTERA CALIZAS' },
    { codigo: 'NOVALO003', nombre: 'CANTERA PUZOLANA' },
    { codigo: 'NOVALO004', nombre: 'POLVO FILLER' },
    { codigo: 'NOVALO005', nombre: 'CANTERA ARCILLAS' },
    { codigo: 'NOVALO006', nombre: 'CANTERAS OXIDOS DE FIERRO' },
    { codigo: 'NOVALO007', nombre: 'CANTERA SILICES' },
    { codigo: 'NOVALO008', nombre: 'CANTERA YESOS' },
    { codigo: 'NOVALO009', nombre: 'PROYECTOS' },
    { codigo: 'NOVALO010', nombre: 'MAT BLOQUETERA' },
  ],
  'Z012': [
    { codigo: 'MERCEM001', nombre: 'MERCADERIAS UNACEM GEA' },
    { codigo: 'MERCEM002', nombre: 'MERCADERIAS UNACEM PREANSA' },
    { codigo: 'MERCEM003', nombre: 'MERCADERIAS HORMIGON' },
  ],
  'Z013': [
    { codigo: 'SERVIC001', nombre: 'ARRENDAMIENTO, EDIFICACIONES Y TERRENOS' },
    { codigo: 'SERVIC002', nombre: 'CONTRIBUCION / SIST. AISLADOS' },
    { codigo: 'SERVIC003', nombre: 'ENERGIA' },
    { codigo: 'SERVIC004', nombre: 'INTERESES' },
    { codigo: 'SERVIC005', nombre: 'REEMBOLSOS' },
    { codigo: 'SERVIC006', nombre: 'VTA DE EQ. HERRAM Y MAQ.' },
    { codigo: 'SERVIC007', nombre: 'ALQ DE EQ. HERRAM Y MAQ' },
    { codigo: 'SERVIC008', nombre: 'SEGUROS' },
    { codigo: 'SERVIC009', nombre: 'SERV. ADMINISTRATIVOS INTEGRALES' },
    { codigo: 'SERVIC010', nombre: 'EXPORT. TEMPORAL' },
    { codigo: 'SERVIC011', nombre: 'SERV. OPERAC. PORTUARIAS' },
    { codigo: 'SERVIC012', nombre: 'ALQUILER PLANTA GEA' },
    { codigo: 'SERVIC013', nombre: 'PAVIM O BOMBEO DE CONCRETO M3' },
    { codigo: 'SERVIC014', nombre: 'RECARGOS MINIMOS HORMIGON' },
    { codigo: 'SERVIC015', nombre: 'VTA. HORMIGON' },
    { codigo: 'SERVIC016', nombre: 'VTA. DER. HORMIGON' },
    { codigo: 'SERVIC017', nombre: 'VTA. CHATARRA FIERROS' },
    { codigo: 'SERVIC099', nombre: 'VARIOS - SERVICIOS VTA' },
  ],
  'Z014': [
    { codigo: 'SEMCEM001', nombre: 'CLINKER' },
    { codigo: 'SEMCEM002', nombre: 'CALIZAS' },
    { codigo: 'SEMCEM003', nombre: 'PUZOLANA' },
    { codigo: 'SEMCEM004', nombre: 'YESOS' },
    { codigo: 'SEMCEM005', nombre: 'CRUDO' },
    { codigo: 'SEMCEM006', nombre: 'POLVO FILLER' },
    { codigo: 'SEMCEM007', nombre: 'CEMENTOS' },
    { codigo: 'SEMCEM008', nombre: 'HARINA DE CEMENTO' },
    { codigo: 'SEMCEM009', nombre: 'FIERROS' },
    { codigo: 'SEMCEM010', nombre: 'ARCILLAS' },
    { codigo: 'SEMCEM011', nombre: 'CARBON SOLID-PETCOKE' },
    { codigo: 'SEMCEM012', nombre: 'SILICES' },
    { codigo: 'SEMCEM013', nombre: 'BAUXITA' },
    { codigo: 'SEMPRE001', nombre: 'FIERRO HABILITADO' },
    { codigo: 'SEMPRE002', nombre: 'MALLA HABILITADO' },
    { codigo: 'SEMPRE003', nombre: 'HORMIGON' },
  ],
  'Z015': [
    { codigo: 'PTBLOQ001', nombre: 'ADOQUINES' },
    { codigo: 'PTBLOQ002', nombre: 'BLOQUES' },
    { codigo: 'PTBLOQ003', nombre: 'BOVEDILLAS' },
    { codigo: 'PTBLOQ004', nombre: 'LADRILLOS' },
    { codigo: 'PTBLOQ099', nombre: 'VARIOS - PT BLOQUETERA' },
    { codigo: 'PTCEME001', nombre: 'CEMENTO TIPO I' },
    { codigo: 'PTCEME002', nombre: 'CEMENTO TIPO I BA' },
    { codigo: 'PTCEME003', nombre: 'CEMENTO TIPO I Co' },
    { codigo: 'PTCEME004', nombre: 'CEMENTO TIPO I FA' },
    { codigo: 'PTCEME005', nombre: 'CEMENTO TIPO I PM' },
    { codigo: 'PTCEME006', nombre: 'CEMENTO TIPO II' },
    { codigo: 'PTCEME007', nombre: 'CEMENTO TIPO II BA' },
    { codigo: 'PTCEME008', nombre: 'CEMENTO TIPO IP' },
    { codigo: 'PTCEME009', nombre: 'CEMENTO TIPO IS' },
    { codigo: 'PTCEME010', nombre: 'CEMENTO TIPO V' },
    { codigo: 'PTCEME011', nombre: 'CEMENTO TIPO I GU' },
    { codigo: 'PTCEME012', nombre: 'CEMENTO TIPO HS' },
    { codigo: 'PTCEME013', nombre: 'CEMENTO ANDINO FORTE' },
    { codigo: 'PTCEME014', nombre: 'CEMENTO TIPO IL' },
    { codigo: 'PTCEME015', nombre: 'CEMENTO T-N PUZOLANA' },
    { codigo: 'PTCEME016', nombre: 'CEMENTO TIPO III' },
    { codigo: 'PTPREA001', nombre: 'PILARES' },
    { codigo: 'PTPREA002', nombre: 'VIGAS' },
    { codigo: 'PTPREA003', nombre: 'PANELES' },
    { codigo: 'PTPREA004', nombre: 'CAJAS (Box)' },
    { codigo: 'PTAGRE001', nombre: 'AGREGADOS' },
    { codigo: 'PTARCI001', nombre: 'ARCILLA' },
    { codigo: 'PTCALI001', nombre: 'CALIZA' },
    { codigo: 'PTPUZO001', nombre: 'PUZOLANA' },
    { codigo: 'PTTPAL001', nombre: 'TAPA ALVEOLAR' },
    { codigo: 'PTVIGU001', nombre: 'VIGUETA' },
    { codigo: 'PTPRLS001', nombre: 'PRELOSA' },
    { codigo: 'PTLSAL001', nombre: 'LOSA ALVEOLAR' },
    { codigo: 'PTMORE001', nombre: 'MORTERO EMBOLSADO' },
    { codigo: 'PTTARE001', nombre: 'TARRAJEO EMBOLSADO' },
    { codigo: 'PTCONE001', nombre: 'CONCRETO EMBOLSADO' },
    { codigo: 'PTHORM006', nombre: 'HORMIGON BAJA RESISTENCIA' },
    { codigo: 'PTHORM007', nombre: 'HORMIGON AUTOCOMPACTANTE' },
  ],
};
